const locations = [
  'Accra, Ghana',
  'A Coruna, Spain',
  'Agoura Hills, CA',
  'Albany, NY',
  'Albuquerque, NM',
  'Alexandria, LA',
  'Alexandria, VA',
  'Algiers, Algeria',
  'Allentown, PA',
  'Almaty, Kazakhstan',
  'Alpharetta, GA',
  'Amherst, MA',
  'Amsterdam, Netherlands',
  'Ankara, Turkey',
  'Annapolis, MD',
  'Ann Arbor, MI',
  'Arlington, VA',
  'Asheville, NC',
  'Astana, Kazakhstan',
  'Athens, Greece',
  'Atlanta, GA',
  'Atlantic City, NJ',
  'Atyrau, Kazakhstan',
  'Auckland, New Zealand',
  'Augusta, GA',
  'Austin, TX',
  'Bahir Dar, Ethiopia',
  'Bakersfield, CA',
  'Baltimore, MD',
  'Bangalore, India',
  'Bangkok, Thailand',
  'Barcelona, Spain',
  'Basking Ridge, NJ',
  'Baton Rouge, LA',
  'Beaver Creek, CO',
  'Beaverton, MI',
  'Bedminster, NJ',
  'Beijing, China',
  'Belfast, United Kingdom',
  'Bellevue, WA',
  'Bellingham, MA',
  'Bellingham, WA',
  'Belo Horizonte, Brazil',
  'Bend, OR',
  'Berlin, Germany',
  'Billings, MT',
  'Biloxi, MS',
  'Binghamton, NY',
  'Birmingham, AL',
  'Birmingham, MI',
  'Bismarck, ND',
  'Bloomington, IL',
  'Bogota, Colombia',
  'Boise, ID',
  'Bologna, Italy',
  'Bonita Springs, FL',
  'Bordeaux, France',
  'Bossier City, LA',
  'Boston Metro Area',
  'Boulder, CO',
  'Bozeman, MT',
  'Bracknell, United Kingdom',
  'Brampton, Canada',
  'Branchburg, NJ',
  'Branson, MO',
  'Brewer, ME',
  'Bridgeport, CT',
  'Bridgewater, NJ',
  'Brighton, United Kingdom',
  'Brisbane, Australia',
  'Bristol, TN',
  'Bristol, United Kingdom',
  'Brookfield, WI',
  'Brooklyn, NY',
  'Brussels, Belgium',
  'Bucharest, Romania',
  'Budapest, Hungary',
  'Buenos Aires, Argentina',
  'Buffalo, NY',
  'Bungoma, Kenya',
  'Burlington, Canada',
  'Burlington, MA',
  'Burlington, VT',
  'Bursa, Turkey',
  'Busan, South Korea',
  'Calgary, Canada',
  'Calhoun, GA',
  'Canberra, Australia',
  'Cape Town, South Africa',
  'Carrollton, KY',
  'Center Valley, PA',
  'Chandigarh, India',
  'Charleston, SC',
  'Charleston, WV',
  'Charlotte, NC',
  'Charlottesville, VA',
  'Chattanooga, TN',
  'Chengdu, China',
  'Chennai, India',
  'Cherry Hill, NJ',
  'Chestertown, MD',
  'Chevy Chase, MD',
  'Chicago, IL',
  'Chongqing, China',
  'Cincinnati, OH',
  'Clarksburg, WV',
  'Cleveland, OH',
  'Clifton Heights, PA',
  'Coffeyville, KS',
  'College Station, TX',
  'Colorado Springs, CO',
  'Columbia, MO',
  'Columbia, SC',
  'Columbus, GA',
  'Columbus, OH',
  'Copenhagen, Denmark',
  'Cork, Ireland',
  'Corpus Christi, TX',
  'Covington, TN',
  'Crofton, MD',
  'Dallas, TX',
  'Dalton, GA',
  'Daly City, CA',
  'Dartmouth, Canada',
  'Daytona Beach, FL',
  'Delray Beach, FL',
  'Denton, MD',
  'Denver, CO',
  'Des Moines, IA',
  'Detroit, MI',
  'Dhaka, Bangladesh',
  'Dodge City, KS',
  'Dodoma, Tanzania',
  'Draper, UT',
  'Dreieich, Germany',
  'Dubai, United Arab Emirates',
  'Dublin, Ireland',
  'Duluth, MN',
  'Durango, CO',
  'Durham, NC',
  'Dusseldorf, Germany',
  'Eagan, MN',
  'East Stroudsburg, PA',
  'Eatontown, NJ',
  'Eau Claire, WI',
  'Edinburgh, United Kingdom',
  'Edmonton, Canada',
  'El Paso, TX',
  'Englewood Cliffs, NJ',
  'Englewood, CO',
  'Eugene, OR',
  'Evansville, IN',
  'Fairfax, VA',
  'Falls Church, VA',
  'Fargo, ND',
  'Fayetteville, AR',
  'Flemington, NJ',
  'Flexible / Remote',
  'Florence, Italy',
  'Fort Collins, CO',
  'Fort Dodge, IA',
  'Fort Lauderdale, FL',
  'Fort Wayne, IN',
  'Fort Worth, TX',
  'Frankfurt, Germany',
  'Fremont, CA',
  'Fresno, CA',
  'Ft. Myers, FL',
  'Fukuoka, Japan',
  'Galway, Ireland',
  'Gambrills, MD',
  'Glasgow, United Kingdom',
  'Glastonbury, CT',
  'Glendale, CA',
  'Golden, CO',
  'Grand Rapids, MI',
  'Green Bay, WI',
  'Greenville, SC',
  'Guadalajara, Mexico',
  'Guangzhou, China',
  'Guragon, India',
  'Hagatna, Guam',
  'Halifax, Canada',
  'Hamburg, Germany',
  'Hamilton, Bermuda',
  'Hamilton, NJ',
  'Hammond, IN',
  'Hangzhou, China',
  'Hanoi, Vietnam',
  'Hanover, NH',
  'Harker Heights, TX',
  'Harrisburg, PA',
  'Hartford, CT',
  'Helena, MT',
  'Helsinki, Finland',
  'Henderson, NV',
  'Hermosillo, Mexico',
  'Hingham, MA',
  'Ho Chi Minh City, Vietnam',
  'Hong Kong',
  'Honolulu, HI',
  'Houston, TX',
  'Hsinchu, Taiwan',
  'Huntington, WV',
  'Huntsville, AL',
  'Hunt Valley, MD',
  'Hyderabad, India',
  'Independence, MO',
  'Indianapolis, IN',
  'International',
  'Iringa, Tanzania',
  'Irvine, CA',
  'Irving, TX',
  'Istanbul, Turkey',
  'Jackson, MS',
  'Jacksonville, FL',
  'Jakarta, Indonesia',
  'Jefferson City, MO',
  'Jersey City, NJ',
  'Johannesburg, South Africa',
  'Johnstown, PA',
  'Jonesboro, AR',
  'Joplin, MO',
  'Kakamega, Kenya',
  'Kalamazoo, MI',
  'Kampala, Uganda',
  'Kansas City, KS',
  'Kansas City, MO',
  'Kazan, Russia',
  'Kiev, Ukraine',
  'Kigali, Rwanda',
  'Kilbourne, IL',
  'Kitchener, Canada',
  'Knoxville, TN',
  'Krakow, Poland',
  'Kyoto, Japan',
  'Lafayette, LA',
  'Lagos, Nigeria',
  'Lake Tahoe, CA',
  'Lancaster, PA',
  'Landover, MD',
  'Lanham, MD',
  'Las Vegas, NV',
  'Lausanne, Switzerland',
  'Lebanon, NH',
  'Lexington, KY',
  'Lille, France',
  'Lilongwe, Malawi',
  'Lima, OH',
  'Lima, Peru',
  'Lincoln, NE',
  'Lisbon, Portugal',
  'Lisle, IL',
  'Little Rock, AR',
  'London, United Kingdom',
  'Long Island, NY',
  'Los Angeles, CA',
  'Louisville, KY',
  'Lowell, MA',
  'Luxembourg City, Luxembourg',
  'Lyon, France',
  'Macau, Macau',
  'Macon, GA',
  'Madison, WI',
  'Madrid, Spain',
  'Malaga, Spain',
  'Malibu, CA',
  'Malvern, PA',
  'Manchester, NH',
  'Manchester, United Kingdom',
  'Manhattan, NY',
  'Manila, Philippines',
  'Markham, Canada',
  'Marseille, France',
  'McAllen, TX',
  'Medford, OR',
  'Melbourne, Australia',
  'Melbourne, FL',
  'Memphis,TN',
  'Mendoza, Argentina',
  'Menlo Park, CA',
  'Meridian, MS',
  'Mesa, AZ',
  'Mexico City, Mexico',
  'Miami, FL',
  'Midland, MI',
  'Milan, Italy',
  'Milton, DE',
  'Milton Keynes, United Kingdom',
  'Milwaukee, WI',
  'Minneapolis, MN',
  'Minooka, IL',
  'Mississauga, Canada',
  'Mobile, AL',
  'Moccasin, CA',
  'Moncton, Canada',
  'Monterrey, Mexico',
  'Montevideo, Uruguay',
  'Montgomery, AL',
  'Montreal, Canada',
  'Moscow, Russia',
  'Mountain Home, AR',
  'Mountainside, NJ',
  'Mountain View, CA',
  'Mt. Vernon, WA',
  'Multiple',
  'Mumbai, India',
  'Munich, Germany',
  'Muramvya, Burundi',
  'Myrtle Beach, SC',
  'Nagoya, Japan',
  'Nairobi, Kenya',
  'Nanjing, China',
  'Naples, Italy',
  'Nashua, NH',
  'Nashville, TN',
  'Netanya, Israel',
  'Newark, DE',
  'New Berlin, WI',
  'Newcastle, Australia',
  'New Century, KS',
  'New Delhi, India',
  'New Haven, CT',
  'New Orleans, LA',
  'New Rochelle, NY',
  'New York City Metro Area',
  'Nogales, Mexico',
  'Norwalk, CT',
  'Norwich, VT',
  'Novosibirsk, Russia',
  'Oaxaca, Mexico',
  'Odessa, Ukraine',
  'Oklahoma City, OK',
  'Olympia, WA',
  'Omaha, NE',
  'Orange, CA',
  'Orlando, FL',
  'Osaka, Japan',
  'Oshkosh, WI',
  'Oslo, Norway',
  'Ostrava, Czech Republic',
  'Ottawa, Canada',
  'Oxford, NC',
  'Oxford, United Kingdom',
  'Oxnard, CA',
  'Padua, Italy',
  'Palm Bay, FL',
  'Palm Beach, FL',
  'Palm Springs, CA',
  'Palo Alto, CA',
  'Panama City, FL',
  'Paris, France',
  'Parkersburg, WV',
  'Parsippany, NJ',
  'Pasadena, CA',
  'Pasadena, MD',
  'Pensacola, FL',
  'Peoria, IL',
  'Perth, Australia',
  'Philadelphia, PA',
  'Phoenix, AZ',
  'Piscataway, NJ',
  'Pittsburgh, PA',
  'Plano, TX',
  'Plattsburgh, NY',
  'Pleasanton, CA',
  'Portland, ME',
  'Portland, OR',
  'Porto Alegre, Brazil',
  'Prague, Czech Republic',
  'Princeton, NJ',
  'Providence, RI',
  'Provo, UT',
  'Pyay, Myanmar',
  'Quebec City, Canada',
  'Queens, NY',
  'Quito, Ecuador',
  'Ra\'anana, Israel',
  'Raeford, NC',
  'Raleigh, NC',
  'Reading, United Kingdom',
  'Recife, Brazil',
  'Redford, MI',
  'Redlands, CA',
  'Redwood City, CA',
  'Regina, Canada',
  'Rehoboth Beach, DE',
  'Reno, NV',
  'Richmond, VA',
  'Riga, Latvia',
  'Rio de Janeiro, Brazil',
  'Riyadh, Saudi Arabia',
  'Roanoke, VA',
  'Rochester, NY',
  'Rock Island, IL',
  'Rockville, MD',
  'Rogers, AR',
  'Rome, Italy',
  'Roxboro, NC',
  'Rubengera, Rwanda',
  'Sacramento Metro Area',
  'Saguenay, Canada',
  'Saint John, Canada',
  'Saint Louis, MO',
  'Salt Lake City, UT',
  'San Antonio Metro Area',
  'San Clemente, CA',
  'San Diego, CA',
  'San Francisco Bay Area',
  'San Jose, CA',
  'San Luis Obispo, CA',
  'San Mateo, CA',
  'Santa Ana, Costa Rica',
  'Santa Barbara, CA',
  'Santa Cruz, CA',
  'Santa Monica, CA',
  'Santiago, Chile',
  'Sao Paolo, Brazil',
  'Sapporo, Japan',
  'Savannah, GA',
  'Schaumburg, IL',
  'Scottsbluff, NE',
  'Scottsdale, AZ',
  'Scranton, PA',
  'Seattle, WA',
  'Secaucus, NJ',
  'Seoul, South Korea',
  'Severna Park, MD',
  'Seville, Spain',
  'Shanghai, China',
  'Shenzhen, China',
  'Short Hills, NJ',
  'Shreveport, LA',
  'Sikeston, MO',
  'Silicon Valley, CA',
  'Singapore',
  'Sioux City, IA',
  'Sofia, Bulgaria',
  'Spokane, WA',
  'Springfield, IL',
  'Springfield, MO',
  'St. Albans City, VT',
  'Stevensville, MD',
  'St. John\'s, Canada',
  'Stockholm, Sweden',
  'St. Petersburg, Russia',
  'Suffolk, VA',
  'Sugar Valley, GA',
  'Sunnyvale, CA',
  'Surabaya, Indonesia',
  'Swainsboro, GA',
  'Swift Creek, VA',
  'Sydney, Australia',
  'Syracuse, NY',
  'Tahoe City, CA',
  'Taipei, Taiwan',
  'Taizhou, China',
  'Tallahassee, FL',
  'Tallinn, Estonia',
  'Tamarindo, Costa Rica',
  'Tampa, FL',
  'Tel Aviv, Israel',
  'Tempe, AZ',
  'Tijuana, Mexico',
  'Tokyo, Japan',
  'Toledo, OH',
  'Topeka, KS',
  'Toronto, Canada',
  'Traverse City, MI',
  'Trenton, NJ',
  'Trujillo, Peru',
  'Trumbull, CT',
  'Tucson, AZ',
  'Tulsa, OK',
  'Val-d\'Or, Canada',
  'Valencia, Spain',
  'Valletta, Malta',
  'Vancouver, Canada',
  'Vancouver, WA',
  'Venice, Italy',
  'Vienna, Austria',
  'Villahermosa, Mexico',
  'Virginia Beach, VA',
  'Volcano, HI',
  'Warsaw, Poland',
  'Washington DC Metro Area',
  'Waterbury, VT',
  'Waterloo, Canada',
  'Wayne, PA',
  'Wellington, New Zealand',
  'Westlake Village, CA',
  'Westport, CT',
  'Wichita, KS',
  'Wilmington, DE',
  'Wilton, CT',
  'Winnipeg, Canada',
  'Woodcliff Lake, NJ',
  'Wuhan, China',
  'Wuxi, China',
  'Wyomissing, PA',
  'Xi\'an, China',
  'Zomba, Malawi',
  'Zurich, Switzerland',
];

module.exports = locations;
